# Generated by Django 4.1.4 on 2022-12-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=50, verbose_name='Название')),
                ('anons', models.CharField(default='None', max_length=250, verbose_name='Ананонс')),
                ('full_text', models.TextField(verbose_name='Описание статьи')),
                ('datae', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
