# Generated by Django 4.1.4 on 2022-12-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_rename_datae_articles_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вопроса')),
                ('anons', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('ans1', models.TextField(verbose_name='Вариант ответа 1')),
                ('pr1', models.IntegerField(verbose_name='Цена ответа в баллах')),
                ('ans2', models.TextField(verbose_name='Вариант ответа 2')),
                ('pr2', models.IntegerField(verbose_name='Цена ответа в баллах')),
                ('ans3', models.TextField(verbose_name='Вариант ответа 3')),
                ('pr3', models.IntegerField(verbose_name='Цена ответа в баллах')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
